### PR TITLE
Checksync

### PR DESCRIPTION
**Pull request by davidcoutadeur**
First working function, trying to complete:
Add a checksync function in init script or cli script #5

### CODE REVIEW

**Comment by coudot** [comment]
It works better, but still an error at the end:

```
root@ader-sfl:~# sh -x /etc/init.d/slapd checksync                         
+ VERSION=2.2
+ IP=*
+ SSLIP=*
+ PORT=389
+ SSLPORT=636
+ LDAPI_SOCKETDIR=
+ LDAPI_SOCKETURL=
+ SLAPD_PATH=/usr/local/openldap
+ SLAPD_PID_FILE=/usr/local/openldap/var/run/slapd.pid
+ SLAPD_CONF=/usr/local/openldap/etc/openldap/slapd.conf
+ SLAPD_CONF_DIR=
+ SLAPD_SERVICES=ldap://*:389 ldaps://*:636
+ SLAPD_PARAMS=
+ SLAPD_BIN=/usr/local/openldap/libexec/slapd
+ SLAPD_USER=
+ SLAPD_GROUP=
+ SLAPD_SYSLOG_LOCAL_USER=local4
+ DATA_PATH=/usr/local/openldap/var/openldap-data
+ SLAPADD_BIN=/usr/local/openldap/sbin/slapadd
+ SLAPADD_PARAMS=-q
+ SLAPCAT_BIN=/usr/local/openldap/sbin/slapcat
+ SLAPINDEX_BIN=/usr/local/openldap/sbin/slapindex
+ SLAPTEST_BIN=/usr/local/openldap/sbin/slaptest
+ SLURPD_ACTIVATE=0
+ SLURPD_PID_FILE=/usr/local/openldap/var/run/slurpd.pid
+ SLURPD_PARAMS=
+ SLURPD_BIN=/usr/local/openldap/libexec/slurpd
+ BDB_PATH=/usr/local/berkeleydb
+ DB_ARCHIVE_BIN=/usr/local/berkeleydb/bin/db_archive
+ DB_RECOVER_BIN=/usr/local/berkeleydb/bin/db_recover
+ RECOVER_AT_STARTUP=1
+ BACKUP_AT_SHUTDOWN=1
+ BACKUP_PATH=/tmp/openldap
+ date +%Y%m%d%H%M%S
+ BACKUP_SUFFIX=20171212085939.ldif
+ BACKUP_COMPRESS_EXT=
+ BACKUP_COMPRESS_BIN=                                                                                                                                                    
+ BACKUP_UNCOMPRESS_BIN=                                                                                                                                                  
+ TIMEOUT=60                                                                                                                                                              
+ FD_LIMIT=2048                                                                                                                                                           
+ DEBUG_LEVEL=256                                                                                                                                                         
+ basename /etc/init.d/slapd
+ sed s/^[KS][0-9][0-9]//
+ PROG_NAME=slapd
+ uname -s
+ OS=Linux
+ id -u
+ MYUID=0
+ id -g
+ MYGID=0
+ PS_COMMAND=ps -efww
+ declare -a PROVIDER
/etc/init.d/slapd: 112: /etc/init.d/slapd: declare: not found
+ RETVAL=
+ [ -f /etc/default/slapd ]
+ . /etc/default/slapd
+ IP=*
+ SSLIP=*
+ PORT=389
+ SSLPORT=636
+ LDAPI_SOCKETDIR=/var/run/slapd
+ LDAPI_SOCKETURL=%2Fvar%2Frun%2Fslapd%2Fldapi
+ SLAPD_PATH=/usr/local/openldap
+ SLAPD_PID_FILE=/home/clement/configuration/openldap/example/slapd.pid
+ SLAPD_CONF=
+ SLAPD_CONF_DIR=/home/clement/configuration/openldap/example/slapd.d
+ SLAPD_SERVICES=ldap://*:389 ldaps://*:636 ldapi://%2Fvar%2Frun%2Fslapd%2Fldapi
+ SLAPD_PARAMS=
+ SLAPD_BIN=/usr/local/openldap/libexec/slapd
+ SLAPD_USER=clement
+ SLAPD_GROUP=clement
+ SLAPD_SYSLOG_LOCAL_USER=local4
+ DATA_PATH=auto
+ SLAPADD_BIN=/usr/local/openldap/sbin/slapadd
+ SLAPADD_PARAMS=-q
+ SLAPCAT_BIN=/usr/local/openldap/sbin/slapcat
+ SLAPINDEX_BIN=/usr/local/openldap/sbin/slapindex
+ SLAPTEST_BIN=/usr/local/openldap/sbin/slaptest
+ SLURPD_PID_FILE=/usr/local/openldap/var/run/slurpd.pid
+ SLURPD_PARAMS=
+ SLURPD_BIN=/usr/local/openldap/libexec/slurpd
+ BDB_PATH=/usr/local/berkeleydb
+ DB_ARCHIVE_BIN=/usr/local/berkeleydb/bin/db_archive
+ DB_RECOVER_BIN=/usr/local/berkeleydb/bin/db_recover
+ RECOVER_AT_STARTUP=0
+ BACKUP_AT_SHUTDOWN=0
+ BACKUP_PATH=/home/clement/configuration/openldap/example
+ date +%Y%m%d%H%M%S
+ BACKUP_SUFFIX=20171212085939.ldif
+ BACKUP_COMPRESS_EXT=
+ BACKUP_COMPRESS_BIN=
+ BACKUP_UNCOMPRESS_BIN=
+ TIMEOUT=30
+ FD_LIMIT=1024
+ DEBUG_LEVEL=256
+ message info [INFO] Using /etc/default/slapd for configuration
+ logger -p local4.info -t slapd -i [INFO] Using /etc/default/slapd for configuration
+ [ info = alert ]
+ echo slapd: [INFO] Using /etc/default/slapd for configuration
slapd: [INFO] Using /etc/default/slapd for configuration
+ [ clement -a 0 -eq 0 ]
+ SU=su -s /bin/bash - clement -c 
+ dirname /home/clement/configuration/openldap/example/slapd.pid
+ piddir=/home/clement/configuration/openldap/example
+ [ ! -d /home/clement/configuration/openldap/example ]
+ [ ! -x /usr/local/openldap/libexec/slapd ]
+ [ ! -x /usr/local/openldap/sbin/slapcat ]
+ [ ! -x /usr/local/openldap/sbin/slapindex ]
+ [ ! -x /usr/local/openldap/sbin/slaptest ]
+ [  -a ! -r  ]
+ [ -n  -a ! -d /home/clement/configuration/openldap/example/slapd.d ]
+ [ 0 -ne 0 -a ! -x /usr/local/openldap/libexec/slurpd ]
+ [ /home/clement/configuration/openldap/example/slapd.d -a ! -w /home/clement/configuration/openldap/example/slapd.d ]
+ [ 389 -lt 1024 -a 0 -ne 0 ]
+ [ /var/run/slapd -a ! -r /var/run/slapd ]
+ check_sync
+ message info [INFO] Checking synchronization...
+ logger -p local4.info -t slapd -i [INFO] Checking synchronization...
+ [ info = alert ]
+ echo slapd: [INFO] Checking synchronization...
slapd: [INFO] Checking synchronization...
+ get_provider_config
+ i=0
+ [ /home/clement/configuration/openldap/example/slapd.d ]
+ /usr/local/openldap/sbin/slapcat -n0 -F /home/clement/configuration/openldap/example/slapd.d -o ldif-wrap=no
+ grep -E ^olcSyncrepl
+ PROVIDERS=
+ echo
+ grep -q -E ^olcSyncrepl
+ get_confvalues suffix
+ [ -n /home/clement/configuration/openldap/example/slapd.d ]
+ backconfig_get_values olcSuffix (|(objectclass=olcBdbConfig)(objectclass=olcHdbConfig)(objectclass=olcMdbConfig))
+ [ -z /home/clement/configuration/openldap/example/slapd.d -o ! -d /home/clement/configuration/openldap/example/slapd.d ]
+ slapcat_cmd=/usr/local/openldap/sbin/slapcat -F /home/clement/configuration/openldap/example/slapd.d -b cn=config
+ [ -n (|(objectclass=olcBdbConfig)(objectclass=olcHdbConfig)(objectclass=olcMdbConfig)) ]
+ [ -n su -s /bin/bash - clement -c  ]
+ slapcat_cmd=/usr/local/openldap/sbin/slapcat -F /home/clement/configuration/openldap/example/slapd.d -b cn=config -a '(|(objectclass=olcBdbConfig)(objectclass=olcHdbConfig)(objectclass=olcMdbConfig))'
+ [ -z su -s /bin/bash - clement -c  ]
+ su -s /bin/bash - clement -c /usr/local/openldap/sbin/slapcat -F /home/clement/configuration/openldap/example/slapd.d -b cn=config -a '(|(objectclass=olcBdbConfig)(objectclass=olcHdbConfig)(objectclass=olcMdbConfig))'
+ perl -p0e s/\n //g
+ grep ^olcSuffix:
+ sed s/olcSuffix: //
+ sed s/ /#20/g
+ list=dc=example,dc=com
+ [ -n dc=example,dc=com ]
+ RETVAL=dc=example,dc=com
+ SUFFIX=dc=example,dc=com
+ RES=0
/etc/init.d/slapd: 1196: /etc/init.d/slapd: Bad substitution
```

**Comment by davidcoutadeur** [comment]
@coudot Seems the get_provider_config function does not find out any provider.
1/ You really have no provider -> the script should not send an error
2/ Actually you have a provider configured. Maybe this is a regex matter. Could you check if this command returns anything?
`/usr/local/openldap/sbin/slapcat -n0 -F /home/clement/configuration/openldap/example/slapd.d -o ldif-wrap=no | grep -i -E '^olcSyncrepl' `

**Comment by coudot** [comment]
I indeed have no olcSyncrepl in my configuration, so the script should exit without error. I'll try to look closer when I have time.

**Comment by coudot** [comment]
Another remark: is the use of "declare" mandatory? It requires bash, and our script is a simple /bin/sh shell.

**Comment by davidcoutadeur** [comment]
Yes it is mandatory as it enables the array of providers...
If we respect a pure sh syntax, I'll have to find another way...

**Comment by coudot** [comment]
In this case you must update the shebang

**Comment by davidcoutadeur** [comment]
I have checked different options.
* in bourne shell (sh), there is no array, and I don't see any elegant solution to do so without arrays...
* I didn't noticed the error because on CentOS 6.6, sh is a link to bash, thus bourne shell is already deprecated on an old operating system.
So maybe could we change the default shell to bash? This has strong implications, so maybe could we do some tests before?

**Comment by coudot** [comment]
We can require bash, the initscript is mostly used in our Debian and RPMs packages.

**Comment by davidcoutadeur** [comment]
Done. The feature seems ready... If possible, you may do some tests on a consumer?

**Comment by coudot** [comment]
Tested with a N-way mutlimaster configuration, seems to work. But it could be great to have more information on SID and server in the status line, so we know which check has been done.

**Comment by davidcoutadeur** [comment]
Nice!
Agreed for upgrading the status line: I will check this next week.

**Comment by davidcoutadeur** [comment]
Now there is more information on stdout while checking synchronization status

**Comment by coudot** [comment]
Some more remarks:
* If there is no associated provider, the checksync exits successfully with this message:
```
root@ader-sfl:~# /etc/init.d/slapd checksync
slapd: [INFO] Using /etc/default/slapd for configuration
slapd: [INFO] Checking synchronization...
slapd: [OK] Local directory synchronized to every declared provider
```
* If one of the directory is stopped, we have this output:
```
root@ader-sfl:~# /etc/init.d/slapd-minint-data-1 checksync
slapd-minint-data-1: [INFO] Using /etc/default/slapd-minint-data-1 for configuration                                                                                      
slapd-minint-data-1: [INFO] Checking synchronization...                                                                                                                   
Checking host ldap://ldap-data-1.minint.local                                                                                                                             
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)                                                                                                                    
Checking host ldap://ldap-data-2.minint.local                                                                                                                             
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)                                                                                                                    
slapd-minint-data-1: [OK] Local directory synchronized to every declared provider 
```
So we should maybe hide the error (2>/dev/null) and print an appropriate status.

**Comment by davidcoutadeur** [comment]
Concerning the 2 latest remarks:
* If there is no associated provider, the checksync exits successfully as intended. Indeed, the slave is either synchronized with its providers, either there is no synchronisation configuration at all. In any case, the slave *is* synchronized with its declared providers. The fact that there is no synchronization configuration makes the checksync command useless, which the administrator is often fully aware of.
* If one of the directory is stopped, [...] -> the new commit is fixing this issue.

**Comment by davidcoutadeur** [comment]
Is it ok for you?
Do you plan other tests?

**Comment by coudot** [comment]
Ok for the second point. For the first point, you are technically right, but I find it more clear if we have a message like [OK] No providers found in configuration - sync status not checked

The admin may launch the command on a lot of VM in a cluster, it is better to have a different status line between masters ans slaves.

**Comment by davidcoutadeur** [comment]
Fair point... It is fixed in latest commit

**Comment by coudot** [comment]
Great! I let you merge (you should have the rights to do it)

**Pull request merged**
