### PR TITLE
Manage spaces and quoted values in syncrepl configuration (ltb-project#13)

### PR DESCRIPTION
**Pull request by coudot**

### CODE REVIEW

**Comment by coudot** [comment]
Hello @davidcoutadeur, if you have some time now, could you review my code proposal?

**Comment by davidcoutadeur** [comment]
@coudot Taking a look

**Comment by coudot** [comment]
Thanks!

> I didn't test the code

I did with different cases (quotes, no quotes, spaces, etc.)

> you declared syncrepl and parameter variables in the function to make it clearer, but keep using $1 and $2

Indeed, I fixed that

> I had a doubt that simple quotes can be used to surround the values, but happily simple quotes are unauthorized

I also tested that and simple quotes are refused by OpenLDAP, so we can rely only on double quotes

**Comment by davidcoutadeur** [comment]
Solve issue #13

**Pull request merged**
